#!/bin/sh
set -e

case "$1" in
	configure)
		update-rc.d tuquito-update start 52 S .
	;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	triggered)
		/usr/lib/tuquito/tuquito-update/update-manager.py time
	;;
	*)
		echo "postinst called with unknown argument '$1'" >&2
		exit 1
	;;
esac

exit 0

