#!/bin/sh
set -e

case "$1" in
	configure)
		update-rc.d tuquitoUpdate start 51 S .
	;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	triggered)
		/usr/lib/tuquito/tuquito-update/tuquito-update.py
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

exit 0

